import sys
import os
sys.path.append(os.path.abspath(os.path.dirname(__file__)))

import numpy as np
import plotly.graph_objects as go
from report_gen import generate_advanced_pdf_report

clinical_data = np.array([[32, 24.5, 8, 7, 0, 1, 65.0, 250.0, 12.0]])
p_prob = 0.85
p_std = 0.05
stage_names = ["None/Minimal", "Stage I (Minimal)", "Stage II (Mild)", "Stage III (Moderate)", "Stage IV (Severe)"]
p_stage = 3
f_risk = np.array([0.9, 0.95, 0.99])
report_text = "This is a test report text generated by the AI."
patient_plan = "This is a test patient plan generated by the AI."

# Mock figures
fig_3d = go.Figure(data=[go.Scatter3d(x=[1,2,3], y=[1,2,3], z=[1,2,3], mode='markers')])
fig_radar = go.Figure(data=go.Scatterpolar(r=[1, 5, 2], theta=['A', 'B', 'C'], fill='toself'))
fig_heat = go.Figure(data=go.Heatmap(z=[[1, 20, 30], [20, 1, 60], [30, 60, 1]]))
fig_xai = go.Figure(data=[go.Bar(x=['Feature A', 'Feature B'], y=[0.5, 0.3])])
explanation = "This is a test XAI explanation."

try:
    print("Generating PDF...")
    pdf_bytes = generate_advanced_pdf_report(
        clinical_data, p_prob, p_std, stage_names, p_stage, f_risk,
        report_text, patient_plan, fig_3d, fig_radar, fig_heat, fig_xai, explanation
    )
    with open("test_report.pdf", "wb") as f:
        f.write(pdf_bytes)
    print(f"Successfully generated PDF: {len(pdf_bytes)} bytes")
except Exception as e:
    print(f"FAILED: {e}")
